version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"  # Ollama keeps this host port
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Changed: Host port 3000 → Container port 11434
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - OLLAMA_HOST=http://ollama:11434
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - ollama
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      # FIXED: Changed from localhost:11434 to ollama:11434
      test: ["CMD", "curl", "-k", "-f", "http://ollama:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  ollama_data: